[package]
name = "wuerfel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.8.5" 


[[bin]]
name = "w6"
path = "src/w6.rs"

[[bin]]
name = "w6c"
path = "src/w6c.rs"
